#!/bin/sh

if [[ "$(uname)" == Linux ]]; then
  PACKAGES_DIR="$HOME/.config/sublime-text-3/Packages"
else
  PACKAGES_DIR="$HOME/Library/Application Support/Sublime Text 3/Packages"
fi

cp -v nix.tmLanguage "$PACKAGES_DIR"
