<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nix</string>
	</array>
	<key>name</key>
	<string>Nix</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#primitives</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#attrset</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#path</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#let</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#indented_string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#attrname</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attrname</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\w|_)(\w|\d|_|-|')*</string>
					<key>name</key>
					<string>support.variable</string>
				</dict>
			</array>
		</dict>
		<key>attrset</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#name_bindings</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#.*</string>
					<key>name</key>
					<string>comment</string>
				</dict>
			</array>
		</dict>
		<key>indented_string</key>
		<dict>
			<key>begin</key>
			<string>''</string>
			<key>end</key>
			<string>(?&lt;![^']')''(?!'|\$\{|\\(n|r|t))</string>
			<key>name</key>
			<string>string</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>''('|\\(n|r|t)|\$\{)</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interp</string>
				</dict>
			</array>
		</dict>
		<key>interp</key>
		<dict>
			<key>begin</key>
			<string>\$\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>foo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>punctuation.section.embedded.nix</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>let</key>
		<dict>
			<key>begin</key>
			<string>let</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>end</key>
			<string>in</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#name_bindings</string>
				</dict>
			</array>
		</dict>
		<key>name_bindings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>(\?|!=?|==?|//?|\+\+?|\|\|)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<key>path</key>
		<dict>
			<key>match</key>
			<string>\.+/[^; ]+</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<key>primitives</key>
		<dict>
			<key>match</key>
			<string>(true|false|import|if|then|else|rec|inherit|null|or)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interp</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.nix</string>
	<key>uuid</key>
	<string>671e7a18-04ae-44d7-8b1c-e11d9f3ef973</string>
</dict>
</plist>
